# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

# Coverage targets
coverage:
  status:
    project:
      default:
        target: 90%                    # Overall project coverage target
        threshold: 1%                  # Allow 1% drop before failing
        informational: false           # Fail PR if coverage drops below target
    patch:
      default:
        target: 85%                    # New code coverage target
        threshold: 5%                  # Allow 5% variance for patches
        informational: true            # Don't block PR on patch coverage

# PR comment configuration
comment:
  layout: "header, diff, flags, components, files, footer"
  behavior: default                    # Update existing comment
  require_changes: false               # Always comment on PRs
  require_base: false                  # Comment even without base commit
  require_head: true                   # Only comment when head coverage available

# Ignore paths in coverage reports
ignore:
  - "**/*.test.tsx"
  - "**/*.test.ts"
  - "**/vitest.setup.ts"
  - "**/vitest.config.ts"
  - "**/*.config.*"
  - "scripts/**"
  - "coverage/**"
  - ".next/**"
  - "node_modules/**"

# GitHub status checks
github_checks:
  annotations: true                    # Show coverage annotations on PR files
